<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>DW2ModLauncher.Core</RootNamespace>
    <AssemblyName>DW2ModLauncher.Core</AssemblyName>
  </PropertyGroup>

</Project>
